version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app
hooks:
  BeforeInstall:
    - location: scripts/BeforeInstall.sh
      timeout: 120
      runas: root
  AfterInstall:
    - location: scripts/AfterInstall.sh
      runas: ubuntu
