version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: scripts/BeforeInstall.sh
      timeout: 120
      runas: ubuntu
  AfterInstall:
    - location: scripts/AfterInstall.sh
      timeout: 120
      runas: ubuntu
