version: 0.2
phases:
  install:
    runtime-versions:
      php: 7.3
      nodejs: 10
  pre_build:
    commands:
      - composer install
  build:
    commands:
      - [ -e .env ] && rm .env
      - touch .env
      - echo 'DB_DATABASE=$DATABASE_URL' >> .env
      - echo 'DB_USERNAME=$DATABASE_USERNAME' >> .env
      - echo 'DB_PASSWORD=$DATABASE_PASSWORD' >> .env
      - php artisan key:generate
      - php artisan config:cache
      - php artisan route:cache
